import type { NextPage } from 'next';
import Head from 'next/head';
import tw from 'twin.macro';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Planning Poker</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Main>Is this Roboto?</Main>
		</>
	);
};

export default Home;

const Main = tw.main``;
